### ISSUE TITLE
Features, Requests, Galore

### ISSUE THREAD

**Issue by AarushX** [AarushX/DerivativeMC#1]
All help appreciated, and much help needed!

**Comment by AarushX** [comment]
lets do this

**Comment by lodenrogue** [comment]
Sure. What new feature did you have in mind?

**Comment by AarushX** [comment]
i was thinking about slowly changing this "downloader" into more of a "launcher"
Some features along the way would be:
> A revamped GUI that resonates professional and modern ([Lunar Client](https://www.lunarclient.com/) is a good example)
> Improved performance across the board by using better methods (the code we have currently is pretty sloppy)
> Executables across platforms (py / exe + dmg)
> A settings page to allow users to change preferences
> A better way to view github tags without being charged against the rate limit
These are good starting points.

Thanks for the eagerness @lodenrogue! :)

**Comment by AarushX** [comment]
Replaced in all functionality [here](https://github.com/AlphaUpstream/Fusion)
